on:
  release:
    types: [published]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Docker Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/epa-dashboard:latest .

      - name: Docker Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/epa-dashboard:latest

      - name: Deploy
        run: |
          gcloud run deploy epa-dashboard \
          --region us-central1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/epa-dashboard \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
